# Generated by Django 4.2.11 on 2024-05-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_id',
        ),
    ]
