# Generated by Django 4.2.11 on 2024-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_article_id_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='articles.hashtag'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='name',
            field=models.CharField(default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
