# Generated by Django 4.2.11 on 2024-05-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_like_users_comment_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/article'),
        ),
    ]
